version: '3.7'

services:
  app-server:
    image: 003235076673.dkr.ecr.us-east-1.amazonaws.com/peermentoring-backend:latest
    ports:
      - "8080:8080"
    restart: always
    environment: 
      DB_URL: terraform-20210708150334350800000001.crro84grzztx.us-east-1.rds.amazonaws.com
      DB_USERNAME: codecool
      DB_PASSWORD: Codecool12
      HIBERNATE_DLL: update
      PROFILE: production
    networks:
      - backend
      - frontend

  app-client:
    image: 003235076673.dkr.ecr.us-east-1.amazonaws.com/peermentoring-frontend:latest
    ports:
      - "9090:80"
    restart: always
    depends_on:
      - app-server
    environment: 
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080
    networks:
      - frontend  

networks:
  backend:
  frontend: